### ISSUE TITLE
Add tests for solvent writers

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#104]
# Description
The classes that write solvent templates need to be tested. We can start by adding a test for the new `OPLSOBC`. Besides, a test for the `OBC2` should also be added.

**Comment by martimunicoy** [comment]
# Support
I attach the templates to be used as reference when validating `OPLSOBC`: [OBC_for_OPLS_test.zip](https://github.com/martimunicoy/peleffy/files/5588676/OBC_for_OPLS_test.zip)

**Comment by laumalo** [comment]
To validate  `OPLOBC` template writer:

```python
from peleffy.tests.test_solvent import TestSolvent

test = TestSolvent()
test.test_OBCOPLS_writer()
```
