### ISSUE TITLE
Unexpected dihedral parameters from Open Force Field Toolkit

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#54]
# Description
We noticed that some of the parameters assigned to torsions by the `Open Force Field Toolkit` are unexpected. The current implementation of `offpele` expects the following values for torsional parameters:
- `phase constant`: either 0.0 or 180.0 degrees
- `periodicity`: one of (1, 2, 3, 4, 6)

See issue #33 for more details.

While the requirement in the `periodicity` value is trivial, the `phase constant` does really need to be either 0.0 or 180.0 degrees. That is because of PELE's current dihedral equation (explained [here](https://eapm-bsc.github.io/PELE-repo/theory/energyFunction.html#the-molecular-mechanics-energy-terms)), which is:

<img src="https://render.githubusercontent.com/render/math?math=U = \sum_{i=1}^\text{dihedrals} \sum_j k_j^i \cdot \left( 1 %2B \text{prefactor}_j^i \cdot \cos \left( \text{periodicity}_j \cdot \phi_i \right) \right)">

Since, there is not a `phase constant` term, we need to use the `prefactor` which can equal 1 or -1. The sign determines whether the shape of the torsion behaves as in `Open Force Field` with a `phase constant` equal to 0.0 or 180.0 degrees. Thus, in case that the `Open Force Field Toolkit` works with `phase` values other than 0.0 and 180.0 degrees we will need to change the equation of dihedrals in `PELE`.

**Comment by martimunicoy** [comment]
Some cases where we have obtained unexpected parameters in torsions:

## Case 1

```
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

mol = Molecule.from_smiles('[H]c1c(sc([n+]1[H])[C@@]2(C(C(=O)N2[H])([H])[H])C([H])([H])[H])[H]')
ff = ForceField('openff_unconstrained-1.2.1.offxml')
topology = Topology.from_molecules([mol])
parameters = ff.label_molecules(topology)[0]
```

- Molecule: [H]c1c(sc([n+]1[H])[C@@]2(C(C(=O)N2[H])([H])[H])C([H])([H])[H])[H]
![image](https://user-images.githubusercontent.com/32293549/93072592-e3209980-f681-11ea-94ab-4e634cb07f19.png)
- Unexpected propers:
    - `t26`, `phase=270.0 deg`, `periodicity=4`
    - `t26`, `phase=270.0 deg`, `periodicity=2`
    - `t26`, `phase=270.0 deg`, `periodicity=1`
<img width="152" alt="image" src="https://user-images.githubusercontent.com/32293549/93073101-af923f00-f682-11ea-8170-2220b772f942.png">

![image](https://user-images.githubusercontent.com/32293549/93073192-cdf83a80-f682-11ea-9c45-b81669a5f219.png)

![image](https://user-images.githubusercontent.com/32293549/93073201-d51f4880-f682-11ea-87d8-d4fb1e3b8248.png)

![image](https://user-images.githubusercontent.com/32293549/93073212-d81a3900-f682-11ea-9ad5-ccb8d56b9b24.png)

## Case 2

```
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

mol = Molecule.from_smiles('[H]c1c(onc1C2(C(C2([H])[H])([H])[H])C(=O)O[H])[H]')
ff = ForceField('openff_unconstrained-1.2.1.offxml')
topology = Topology.from_molecules([mol])
parameters = ff.label_molecules(topology)[0]
```
- Molecule: [H]c1c(onc1C2(C(C2([H])[H])([H])[H])C(=O)O[H])[H]
![image](https://user-images.githubusercontent.com/32293549/93073521-5676db00-f683-11ea-8368-4e085a77ddb1.png)
- Unexpected propers:
    - `t42`, `phase=320.0 deg`, `periodicity=2`
    - `t42`, `phase=320.0 deg`, `periodicity=2`
<img width="145" alt="image" src="https://user-images.githubusercontent.com/32293549/93073558-62fb3380-f683-11ea-9c90-2e5d1e145f90.png">

![image](https://user-images.githubusercontent.com/32293549/93073577-68587e00-f683-11ea-841e-467d00eebe25.png)

![image](https://user-images.githubusercontent.com/32293549/93073587-6abad800-f683-11ea-9ce2-72addc6e1fec.png)

## Case 3

```
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

mol = Molecule.from_smiles('[H]c1c(c(n(n1)S(=O)(=O)C([H])([H])C([H])([H])[H])[H])O[H]')
ff = ForceField('openff_unconstrained-1.2.1.offxml')
topology = Topology.from_molecules([mol])
parameters = ff.label_molecules(topology)[0]
```
- Molecule: [H]c1c(c(n(n1)S(=O)(=O)C([H])([H])C([H])([H])[H])[H])O[H]
![image](https://user-images.githubusercontent.com/32293549/93073710-a3f34800-f683-11ea-9421-06346e5905a9.png)
- Unexpected propers:
    - `t142`, `phase=90.0 deg`, `periodicity=3`
<img width="138" alt="image" src="https://user-images.githubusercontent.com/32293549/93073782-ba010880-f683-11ea-9ce1-2c0f26d166d1.png">

![image](https://user-images.githubusercontent.com/32293549/93073791-be2d2600-f683-11ea-98c1-36a5207d20c8.png)

**Comment by j-wags** [comment]
Thanks for the excellent writeup, @martimunicoy. 

I've checked in the [original FFs](https://github.com/openforcefield/openforcefields/blob/master/openforcefields/offxml/openff-1.2.1.offxml#L188) and those phase values are indeed intentional. I apologize -- I was wrong about this previously. I'm happy to see it's a small number of terms, but I had thought that there were none at all :-/ 

Would you be up to chat about this soon? In the next year or two, OpenFF is anticipating adding virtual sites (off center charges) to our FFs. It may be worth looking at having PELE energy evaluations in OpenMM, since we work with their development team, and will ensure that it can handle any terms in the force fields we release.

**Comment by martimunicoy** [comment]
Thanks for your comment, @j-wags.

I guess we will have to modify the current implementation of the torsion equation in PELE. I have already started looking into a workaround. Besides, once you release a FF with virtual sites we will have to implement them into PELE too. Although it seems you do not plan to release a FF with virtual sites anytime soon, we can already start looking at it.

We can talk about it this current week, if it suits you (either Wednesday, Thursday or Friday).

Thank you again!:)

**Comment by j-wags** [comment]
Great. I'll coordinate the meeting on Slack :-)
