### ISSUE TITLE
Impact class needs to be tested

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#65]
# Description
Currently, `Impact` class is not tested. We should design some tests to check it out.

**Comment by martimunicoy** [comment]
# Cases to be tested
- [ ] Impact template should complain when a non parameterized molecule is fetched.
- [ ] Writer should be tested

**Comment by martimunicoy** [comment]
# Support
Set of three templates to use as reference: [reference_templates.zip](https://github.com/martimunicoy/offpele/files/5465722/reference_templates.zip)
- `metz`: corresponds to the template we expect to obtain when loading the following molecule
```python
from offpele.topology import Molecule
from offpele.utils import get_data_file_path
from offpele.template import Impact

pdb_path = get_data_file_path('ligands/methane.pdb')
m = Molecule(pdb_path)
m.parameterize('openff_unconstrained-1.2.1.offxml')

impact = Impact(m)
```

- `malz`: corresponds to the template we expect to obtain when loading the following molecule
```python
from offpele.topology import Molecule
from offpele.utils import get_data_file_path
from offpele.template import Impact

pdb_path = get_data_file_path('ligands/malonate.pdb')
m = Molecule(pdb_path)
m.parameterize('openff_unconstrained-1.2.1.offxml')

impact = Impact(m)
```

- `etlz`: corresponds to the template we expect to obtain when loading the following molecule
```python
from offpele.topology import Molecule
from offpele.utils import get_data_file_path
from offpele.template import Impact

pdb_path = get_data_file_path('ligands/ethylene.pdb')
m = Molecule(pdb_path, tag='ETL')  # Note that in this case we are assigning a tag to the molecule which will be used in the Impact template
m.parameterize('openff_unconstrained-1.2.1.offxml')

impact = Impact(m)
```

**Comment by laumalo** [comment]
## Implementation

- **Example**

```
from test_templates import TestImpactTemplate

test = TestImpactTemplate()
test.test_input()
test.test_writer()
```

**Comment by martimunicoy** [comment]
# Support 2

I am attaching three reference Impact templates (corresponding to the ligands introduced in my previous post) obtained with the OPLS2005 force field: [OPLS_reference_templates.zip](https://github.com/martimunicoy/offpele/files/5474515/OPLS_reference_templates.zip)
