### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#72]
This package is no longer exclusively employing OpenFF force fields (as it can also employ OPLS2005). Thus, its name should be more general.

Some proposals:
- `pelep`: PELE Parameterizer
- `pelepar`: PELE PARameterizer
- `peleup`: PELE Universal Parameterizer
- `param2pele`: PARAMeters to PELE
- `peleffy`: PELE Force Field Yielder
- `pelet`: PELE Templatizer

**Comment by SergiR1996** [comment]
I prefer `peleup`, `peleffy`, and `pelet`. I think `pelep` can be confused with the PELE Platform. I also like the `param2pele` name version.
