### ISSUE TITLE
Check out input PDB files prior parameterizing

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#77]
# Description
For instance, `offpele` would fail if the input PDB that contains the ligand to parameterize has atoms with unconsistent residue names. The exception raised in this case is totally misleading. 

# Solution
Implement a safety check for PDB files in order to properly handle exceptions related with its format prior running the parameterization.

**Comment by martimunicoy** [comment]
# Support
List of features to check in the input PDB:

- [ ] All atom names need to be unique. Otherwise raise `Exception('Ligand in input PDB has no unique atom names')`
- [ ] All residue ids must match. Otherwise raise `Exception('A single ligand with immutable residue ids is expected')`
- [ ] All residue names must match. Otherwise raise `Exception('A single ligand with immutable residue names is expected')`

**Comment by laumalo** [comment]
# Implementation

The function [`_PDB_chekup(path)`](https://github.com/martimunicoy/peleffy/blob/fc9e4af95ddce230cc138cdae9edce27e34d709c/peleffy/topology/molecule.py#L574-L601) has been included in the class `Molecule`. 
An it runs prior running the parametrization [here](https://github.com/martimunicoy/peleffy/blob/fc9e4af95ddce230cc138cdae9edce27e34d709c/peleffy/topology/molecule.py#L618-L619).  
```python
#Validate PDB
self._PDB_checkup(path)
```

## Examples

- For the following PDB file in which the atom name `C1` is repeted:

```
HETATM    1  C1  UNK     1       0.634  -0.083   0.007  1.00  0.00           C  
HETATM    2  C1  UNK     1      -0.671   0.098  -0.007  1.00  0.00           C  
HETATM    3  H1  UNK     1       1.354   0.739   0.049  1.00  0.00           H  
HETATM    4  H2  UNK     1       1.082  -1.071  -0.022  1.00  0.00           H  
HETATM    5  H3  UNK     1      -1.096   1.088   0.022  1.00  0.00           H  
HETATM    6  H4  UNK     1      -1.302  -0.770  -0.049  1.00  0.00           H  
CONECT    1    2    2    3    4
CONECT    2    5    6
END
```
It raises the exception:
```
AssertionError: Ligand in input PDB has no unique atom names
```

- For the following PDB file in which the residue id for the atom  `H3` does not match:
```
HETATM    1  C1  UNK     1       0.634  -0.083   0.007  1.00  0.00           C  
HETATM    2  C2  UNK     1      -0.671   0.098  -0.007  1.00  0.00           C  
HETATM    3  H1  UNK     1       1.354   0.739   0.049  1.00  0.00           H  
HETATM    4  H2  UNK     1       1.082  -1.071  -0.022  1.00  0.00           H  
HETATM    5  H3  UNK     2      -1.096   1.088   0.022  1.00  0.00           H  
HETATM    6  H4  UNK     1      -1.302  -0.770  -0.049  1.00  0.00           H  
CONECT    1    2    2    3    4
CONECT    2    5    6
END
```

It raises the exception: 
```
AssertionError: A single ligand with immutable residue ids is expected
```

- For the following PDB file in which the residue name for the atom  `H1` does not match:
```
HETATM    1  C1  UNK     1       0.634  -0.083   0.007  1.00  0.00           C  
HETATM    2  C2  UNK     1      -0.671   0.098  -0.007  1.00  0.00           C  
HETATM    3  H1  UNN     1       1.354   0.739   0.049  1.00  0.00           H  
HETATM    4  H2  UNK     1       1.082  -1.071  -0.022  1.00  0.00           H  
HETATM    5  H3  UNK     1      -1.096   1.088   0.022  1.00  0.00           H  
HETATM    6  H4  UNK     1      -1.302  -0.770  -0.049  1.00  0.00           H  
CONECT    1    2    2    3    4
CONECT    2    5    6
END
```
It raises the exception: 
```
AssertionError: A single ligand with immutable residue names is expected
```
