### ISSUE TITLE
Integrate method for the OPLS OBC parameters

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#78]
# Description
`PELE` has a script to obtain the OBC parameters given a small molecule. This script is quite old though and presents many compatibility problems. Maybe we can incorporate this script into the `offpele` package to automatize the parameterization workflow. We could also look at its compatibility issues to try to improve it.

# Solution
This would be a new `Solvent` class, that given a `Molecule` representation, parameterized with `OPLS2005` would use atom types to assign the OBC parameters. Then, it should write the template file in the corresponding format file expected by PELE.

**Comment by martimunicoy** [comment]
# Support

A new branch called `OBC_for_OPLS` has been created. It contains a new method called [`_add_GBSA_solvent_parameters()`](https://github.com/martimunicoy/peleffy/blob/65a6a27fc2a003b7acffba865c7ae6591813cbbb/peleffy/forcefield/parameters.py#L771) to be filled with the parameterization pipeline from the [solventOBCParamsGenerator.py](https://github.com/EAPM-BSC/PELE-repo/blob/master/scripts/solventOBCParamsGenerator.py) script.

**Comment by martimunicoy** [comment]
The original script required atom degrees to perform the parameterization. Consequently, we need method to extract atom degrees from our molecule representation. This can be done with `RDKit` in a very straightforward way:
```python
rdkit_molecule = molecule.rdkit_molecule

atom_degrees = list()

for atom in rdkit_molecule.GetAtoms():
    atom_degrees.append(atom.GetDegree())
```

**Comment by martimunicoy** [comment]
Besides, in case the parent atom of any atom is needed (for instance, thinking on identifying the atom a hydrogen atom is bonded to), the `Atom`'s attribute `parent` stores the index of the its parent atom. This attribute is set when initializing the `Molecule` representation in `peleffy`.

**Comment by laumalo** [comment]
## Implementation

The method [_add_GBSA_solvent_parameters()](https://github.com/martimunicoy/peleffy/blob/OBC_for_OPLS/peleffy/forcefield/parameters.py#777) has been filled with the parameterization pipeline from the `solventOBCParamsGenerator.py` script.

Only one different feature from the `solventOBCParamsGenerator.py` script has been introduced: 

- When only one of the two parameters is found, the default parameters are returned. In the `solventOBCParamsGenerator.py` script, the parameter found was return and the non-found parameter was not defined. 

## Tests
The function [`test_add_GBSA_solvent_parameters`](https://github.com/martimunicoy/peleffy/blob/OBC_for_OPLS/peleffy/tests/test_forcefields.py#L302) has been implemented and tests the new method for adding the GBSA solvent parameters for the following ligands: `methane.pdb`, `melatone.pdb` and `ethylene.pdb`.
