### ISSUE TITLE
Allow the assignment of external partial charges

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/peleffy#80]
# Description
`PlopRotTemp` allows the assignment of partial charges coming from external suites such as Jaguar. We need to implement this feature in `offpele` too.

# Solution
A new `Charge` method that would read an external file containing the partial charges to assign to the `Molecule` representation.

**Comment by martimunicoy** [comment]
To deal with this issue, we need at least on example of:
- A molecule to parameterize
- The output file of the QM program (e.g. Jaguar) with the partial charges to assign to the previous molecule.

Maybe you, @SergiR1996, can get one (attach it here if so, thanks!).

**Comment by SergiR1996** [comment]
Ok, I attach you several output files from Jaguar (as the QM program) in the _mae_ format.

[Jaguar_mae_output_files.zip](https://github.com/martimunicoy/offpele/files/5466294/Jaguar_mae_output_files.zip)

Hoping they can help!
